= JBoss integration platform BOM
:toc:

Bill Of Materials for SwitchYard, Drools, OptaPlanner, jBPM, ModeShape, Overlord, ...

== Building

----
$ mvn clean install
----

== Usage

The BOM may be imported into your dependency management e.g.

----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.jboss.integration-platform</groupId>
            <artifactId>jboss-integration-platform-bom</artifactId>
            <version>6.0.0-SNAPSHOT</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

NOTE: It is recommended that your project inherits org.jboss:jboss-parent:10 e.g.

----
<parent>
    <groupId>org.jboss</groupId>
    <artifactId>jboss-parent</artifactId>
    <version>10</version>
</parent>
----

== Governance

Discussion mailing list: +jboss-integration-platform-developers+

Any project lead of the Integration Platform (IP) project can change or release the BOM as he/she sees fit,
provided that the following rules have been taking into account:

=== Adding/changing a dependency: conflicts resolution rules

When you want to add or change a dependency X:

. *EAP always wins*: The BOM targets a specific EAP version.
If that EAP version already depends on X, then the BOM must use the same version as EAP.

. *Highest wins*: If the BOM already has another version for dependency X (which means one of the other IP projects already uses it),
then *by default the highest version wins*.

    ** Motivation: The higher version is likely be backwards compatible
    and usually has less bugs and known security holes.

    ** Exception through escalation: If the _losing_ project (with the lower version) disagrees,
    they need to formally escalate and overwrite the version in their pom(s).
    Meanwhile the highest version is used in the BOM.

NOTE: it never hurts to send a mail to the +jboss-integration-platform-developers+ mailing list
to announce you've upgraded a delicate dependency version.

=== Exclusions policy

Dependency exclusions should be avoided, because they cannot be overwritten by child poms.

*A dependency exclusion is only allowed to fix an undisputed bug in the dependency's pom.*
All IP developers needs to unanimous (undisputed) to keep the exclusion.
So as soon as 1 IP developer calls for the removal of an exclusion, he/she can immediately remove it.

=== Version numbering

This BOM has it's own version numbering and release lifecycle.
Any similarity with Drools, jBPM or SwitchYard versions is a coincidence.

If you release the BOM, bump the version number.

== Releasing

To mimic a release without pushing any changes:

----
$ mvn clean install
$ mvn release:prepare -DdryRun
$ mvn release:clean
----

To actually release:

----
$ mvn release:prepare
$ mvn release:perform
----

Then go to https://repository.jboss.org/nexus/[Nexus] and log in.
Find your staging repository to close and release it.
