= JBoss integration platform BOM
:toc:

Bill Of Materials for SwitchYard, Drools, OptaPlanner, jBPM, ModeShape, Overlord, ...

== Goal

Align the dependencies of the Integration Platform projects early on in the development lifecycle.

== Building

----
$ mvn clean install
----

== Usage

There are two ways that a project can use this BOM. Each approach has different benefits and difficulties,
so be sure to evaluate both options and pick the one that works best for your project.

=== Importing

The first option is to _import_ the BOM into your project's +dependencyManagement+ section:

----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.jboss.integration-platform</groupId>
            <artifactId>jboss-integration-platform-bom</artifactId>
            <version>6.0.0-SNAPSHOT</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
----

This basically makes all of the dependencies defined in the BOM _available_ so that POMs in your project
can _use_ dependencies by simply referring just to the +groupId+ and +artifactId+. Th eother attributes
like +version+, +type+, or +scope+ do not have to be repeated in your POMs, since Maven knows about them
from what's in the BOM.

Importing has several benefits:

* Your project POM can have (or inherit from) any parent.
* You can override in your POM any artifact that appears in the BOM by placing the dependency *before*
the imported BOM. Place any project dependencies not found in the BOM *after* the imported BOM.
* Properties defined in the BOM are never seen by the project POM that imports the BOM, and thus will
never interfere with the properties in your project's POM(s). (This is sometimes a good thing.)

However, there are also several disadvantages:

* Properties defined in the BOM are never seen by the project POM that imports the BOM, so it is not
possible to reuse any of those properties. The BOM uses properties to specify the versions of each artifact,
but your POM can see these and will therefore have to define _and maintain_ its own properties. Any
mismatch between these properties can lead to runtime problems that are very difficult to identify.
* The placement of the BOM import with respect to other dependencies in the +dependencyManagement+ section
will affect whether the version in the BOM or in your POM will take precedance. This may lead to your project 
using an unexpected version of a dependency, which can lead to runtime problems that are very difficult to identify.

NOTE: It is recommended that your project inherits +org.jboss:jboss-parent:10+:

----
<parent>
    <groupId>org.jboss</groupId>
    <artifactId>jboss-parent</artifactId>
    <version>10</version>
</parent>
----

=== Inheritance

The second option is for your project POM to _inherit_ from the BOM:

----
<parent>
    <groupId>org.jboss.integration-platform</groupId>
    <artifactId>jboss-integration-platform-bom</artifactId>
    <version>6.0.0-SNAPSHOT</version>
</parent>
----

This is especially easy to do if you project already inherits from (or can be changed to inherit from)
+org.jboss:jboss-parent:10+. In such cases, simply replace the project's existing parent with the BOM.

Doing this has several advantages:

* The BOM inherits from +org.jboss:jboss-parent:10+, so everything already defined in +org.jboss:jboss-parent:10+
will continue to be seen by your project's POM.
* All properties defined in +org.jboss:jboss-parent:10+ and in the BOM are visible in your project POMs,
including all properties used to specify artifact versions.
* There are two ways to force using a different version of an artifact than what is specified in the BOM,
  ** Define in your project's POM the same property that is used in the BOM to specify that artifact's version,
  but specify the desired version for the property in your project's POM.
  ** Specify the dependency and its version in your project POM's +dependencyManagement+ section. This is needed
  if your project wants to exclude transitive dependencies of this artifact.
* All dependencies specified with a version in the +dependencyManagement+ section will _always override_ those 
defined in the parent BOM.

But this approach also has a limitation:

* If your project had a parent other than the +org.jboss:jboss-parent:10+, this approach will not work
unless the old parent can be modified to inherit from the BOM.


== Governance

Discussion mailing list: +jboss-integration-platform-developers+

Any project lead of the Integration Platform (IP) project can change or release the BOM as he/she sees fit,
provided that the following rules have been taken into account:

=== Adding/changing a dependency

When you want to add or change a dependency X:

. Send in a pull request (PR) with the changes you propose.

. All project leads will review the changes and *_acknowledge the PR in principle_*,
which means they have the intention to accept the change.

    ** A project lead will normally not actually test the changes on his project (as that's not practical):
    So he reserves the right to submit a pull request to revert the changes later on.

    ** Most projects do not depend on the bom's +SNAPSHOT+ directly, to avoid sudden surprises.
    Instead they depend on a released version or on a timestamped snapshot (from
    https://repository.jboss.org/nexus/content/groups/public/org/jboss/integration-platform/jboss-integration-platform-bom/6.0.0-SNAPSHOT/[this list]).
    They then update their bom dependency's version frequently, after testing the impact locally.

    ** ACK's are done by commenting on the PR, not on the mailing list.

    ** If a project lead (or his deputy) doesn't acknowledge in reasonable time, chase him for an answer.

    ** Any project lead can reject the PR if he gives a good reason.

        *** On the +master+ branch, no PR can be rejected due to time concerns (deadlines, no time to review, PTO, ...)
        because any project/product that is about to release should be using the release branch.

. After all project leads have acknowledge the PR in principle, merge the changes.

IMPORTANT: *EAP always wins*: The BOM targets a specific EAP version.
If that EAP version already depends on X, then the BOM must use the same version as EAP.

IMPORTANT: In the public bom, a dependency version must _never_ end with +-redhat-0+, +-redhat-1+, etc.
The public bom cannot depend on productization builds,
as anyone should be able to build all its dependencies from source.

NOTE: During conflicts, (all things being equal) prefer the latest and greatest version of a dependency in the BOM.

=== Exclusions policy

Dependency exclusions should be avoided, because they cannot be overwritten by child poms.

*A dependency exclusion is only allowed to fix an undisputed bug in the dependency's pom.*
All IP developers needs to unanimous (undisputed) to keep the exclusion.
So as soon as 1 IP developer calls for the removal of an exclusion, he/she can immediately remove it.

=== Branching policy

The +master+ branch is never released. Release are done from a release branch.
The integration platform has multiple projects, but they use the same bom.
So there are no parallel release branches. There is only 1 latest release branch.

The release branch names simply increment the minor version number.
The correlation between the bom version and project/product versions is below in the section "version mapping".

=== Version numbering

This BOM has it's own version numbering and release lifecycle.
Any similarity with Drools, jBPM or SwitchYard versions is a coincidence.

If you release the BOM, bump the hotfix version number.

== Release procedure

To mimic a release without pushing any changes:

----
$ mvn clean install
$ mvn release:prepare -DdryRun
$ mvn release:clean
----

To actually release:

----
$ mvn release:prepare
$ mvn release:perform
----

Then go to https://repository.jboss.org/nexus/[Nexus] and log in.
Find your staging repository, close it and release it.

=== Version mapping

This section records which project/product versions use which bom version.

* bom 6.1

** Not applicable yet

* bom 6.0

** Projects

*** KIE (Drools, jBPM, OptaPlanner) 6.0

** Products

*** BRMS 6.0
